name: Build and deploy the practice project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run npm install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Add lint configuration
        run: npx eslint .
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run npm install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Add lint configuration
        run: npx eslint .
      - name: Test code
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v4
      - name: Install Node JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run npm install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Add lint configuration
        run: npx eslint .
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deployment started"
      - name: Deployment status
        run: echo "Deployment completed successfully"
